on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - name: Get Release Info
        run: |
          {
          echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\//}"
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}"
          echo "OS_NAME=${{ matrix.goos }}"
          } >> "$GITHUB_ENV"
      - name: OS darwin
        if: matrix.goos == 'darwin'
        run: echo "OS_NAME=macOS" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.20.3.linux-amd64.tar.gz"
          extra_files: LICENSE.txt README.md .env.example
          md5sum: false
          build_command: make